common_store_directory = {
    'SOBEYS': 'Grocery',
    "LEONHARD'SCAFE&REST": 'Food Outside',
    'ATLANTICSUPERSTORE': 'Grocery',
    'AMAZON.CA': 'Household Goods',
    'BELL MOBILITY': 'Cell Phone',
    'LEEZEN': 'Grocery',
    'GREATENLIGHTENMENT': 'Donation',
    'DOLLARAMA': 'Household Goods',
    'A&W': 'Food Outside',
    'SHOPPERSDRUGMART': 'Medicine',
    'GLOBALGROCERYSTORE': 'Grocery',
    'TAKESUSHI': 'Food Outside',
    'PETRO-CANADA': 'Gas',
    'IKYUNOODLESLIMITED': 'Food Outside',
    'STARBUCKS': 'Food Outside',
    'IRVING': 'Gas',
    'KATSUSANRESTAURANT': 'Food Outside',
    'BUSPASS': 'Transportation',
    'HTSP-*TRANSIT': 'Transportation',
    'MIKE&ANDREEA': 'Grocery',
    'TIMHORTONS': 'Food Outside',
    'PANDAMART': 'Grocery',
    'EASTLINK': 'Cell Phone',
    'PHOVIETNAMREST': 'Food Outside',
    'SPICEYCHEFREST': 'Food Outside',
    'SAIGONPHOVIETNAMESE': 'Food Outside',
    'IMMIGRATIONCANADA': 'Others',
    'RECEIVERCOFFEE': 'Food Outside',
    'WAL-MART': 'Grocery'
}